#!/bin/bash
# /etc/init.d/timelapse

### BEGIN INIT INFO
# Provides:          timelapse
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to launch a timelapse
### END INIT INFO


case "$1" in
    start)
        echo "Starting timelapse"
        bloub=$(date '+%d-%b-%Y-%X')
        mkdir -p /var/www/$bloub
        echo "Writing in $bloub"
        raspistill -o /var/www/$bloub/tl_%08d.jpg -n -tl 1500 -t 0 -q 15 -e jpg -th none --rotation 270 -w 1200 -h 800 -v
        ;;
    stop)
        echo "Stopping timelapse"
        killall raspistill
        ;;
    *)
        echo "Usage: /etc/init.d/timelapse start|stop"
        exit 1
        ;;
esac

exit 0
